// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7JwCN65kx029Tta5BIl-NarjhwJaRz0M',
    appId: '1:717421670072:web:8758fb2a6c10b798e98e4d',
    messagingSenderId: '717421670072',
    projectId: 'trainapp-90068',
    authDomain: 'trainapp-90068.firebaseapp.com',
    databaseURL: 'https://trainapp-90068-default-rtdb.firebaseio.com',
    storageBucket: 'trainapp-90068.appspot.com',
    measurementId: 'G-CVCT5N27GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQGzt2OWBYMImPthczk2X-5wHgFL1tXWY',
    appId: '1:717421670072:android:af8ebb058aabfc72e98e4d',
    messagingSenderId: '717421670072',
    projectId: 'trainapp-90068',
    databaseURL: 'https://trainapp-90068-default-rtdb.firebaseio.com',
    storageBucket: 'trainapp-90068.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvcZmrqj5IpT1T85DI2lbdHWyhsI4wdTU',
    appId: '1:717421670072:ios:941b1693e1a76f63e98e4d',
    messagingSenderId: '717421670072',
    projectId: 'trainapp-90068',
    databaseURL: 'https://trainapp-90068-default-rtdb.firebaseio.com',
    storageBucket: 'trainapp-90068.appspot.com',
    iosBundleId: 'com.example.trainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvcZmrqj5IpT1T85DI2lbdHWyhsI4wdTU',
    appId: '1:717421670072:ios:989a415e1b2e5b5fe98e4d',
    messagingSenderId: '717421670072',
    projectId: 'trainapp-90068',
    databaseURL: 'https://trainapp-90068-default-rtdb.firebaseio.com',
    storageBucket: 'trainapp-90068.appspot.com',
    iosBundleId: 'com.example.trainApp.RunnerTests',
  );
}
